# QUANTAXIS 从web获取数据教程

核心函数 QA_fetch_get_xxxxxx(数据来源,代码,日期/时间参数...)

## 股票数据

In [7]:
import QUANTAXIS as QA

### 1. 股票列表

In [10]:
QA.QA_fetch_get_stock_list('tdx')

              code  volunit  decimal_point  name    pre_close sse       sec
code   sse
000001 sz   000001      100              2  平安银行   568.002500  sz  stock_cn
000002 sz   000002      100              2  万 科Ａ    23.549999  sz  stock_cn
000004 sz   000004      100              2  国农科技    17.400000  sz  stock_cn
000005 sz   000005      100              2  世纪星源  4034.005625  sz  stock_cn
000006 sz   000006      100              2  深振业Ａ     5.390000  sz  stock_cn
000007 sz   000007      100              2   全新好  1176.037500  sz  stock_cn
000008 sz   000008      100              2  神州高铁     4.220000  sz  stock_cn
000009 sz   000009      100              2  中国宝安     4.590000  sz  stock_cn
000010 sz   000010      100              2  美丽生态     4.600000  sz  stock_cn
000011 sz   000011      100              2  深物业A   952.012500  sz  stock_cn
000012 sz   000012      100              2  南 玻Ａ     4.970000  sz  stock_cn
000014 sz   000014      100              2  沙河股份   616.005000  sz  stock_cn
000016 sz   000016      100              2  深康佳Ａ     4.080000  sz  stock_cn
000017 sz   000017      100              2  深中华A  7746.009375  sz  stock_cn
000018 sz   000018      100              2  神州长城  2818.012500  sz  stock_cn
000019 sz   000019      100              2  深深宝Ａ   232.025000  sz  stock_cn
000020 sz   000020      100              2  深华发Ａ   968.030000  sz  stock_cn
000021 sz   000021      100              2   深科技     6.140000  sz  stock_cn
000022 sz   000022      100              2  深赤湾Ａ    18.650000  sz  stock_cn
000023 sz   000023      100              2  深天地Ａ  1032.050000  sz  stock_cn
000025 sz   000025      100              2  特 力Ａ    26.719999  sz  stock_cn
000026 sz   000026      100              2  飞亚达Ａ     7.430000  sz  stock_cn
000027 sz   000027      100              2  深圳能源     5.290000  sz  stock_cn
000028 sz   000028      100              2  国药一致   280.139999  sz  stock_cn
000029 sz   000029      100              2  深深房Ａ   808.045000  sz  stock_cn
000030 sz   000030      100              2  富奥股份     4.280000  sz  stock_cn
000031 sz   000031      100              2  中粮地产     5.700000  sz  stock_cn
000032 sz   000032      100              2  深桑达Ａ     7.650000  sz  stock_cn
000034 sz   000034      100              2  神州数码  1416.000000  sz  stock_cn
000035 sz   000035      100              2  中国天楹     4.130000  sz  stock_cn
...            ...      ...            ...   ...          ...  ..       ...
603936 sh   603936      100              2  博敏电子    17.770000  sh  stock_cn
603937 sh   603937      100              2  丽岛新材  1752.037500  sh  stock_cn
603938 sh   603938      100              2  三孚股份    25.600000  sh  stock_cn
603939 sh   603939      100              2  益丰药房   344.060001  sh  stock_cn
603955 sh   603955      100              2  大千生态    16.350000  sh  stock_cn
603958 sh   603958      100              2  哈森股份   200.030000  sh  stock_cn
603959 sh   603959      100              2  百利科技    17.860001  sh  stock_cn
603960 sh   603960      100              2  克来机电    31.230000  sh  stock_cn
603963 sh   603963      100              2  大理药业    16.530001  sh  stock_cn
603966 sh   603966      100              2  法兰泰克   200.040000  sh  stock_cn
603968 sh   603968      100              2  醋化股份    17.160000  sh  stock_cn
603969 sh   603969      100              2  银龙股份     7.000000  sh  stock_cn
603970 sh   603970      100              2  中农立华    19.100000  sh  stock_cn
603976 sh   603976      100              2  正川股份  1640.005000  sh  stock_cn
603977 sh   603977      100              2  国泰集团    24.057500  sh  stock_cn
603978 sh   603978      100              2  深圳新星    24.600000  sh  stock_cn
603979 sh   603979      100              2   金诚信   216.007500  sh  stock_cn
603980 sh   603980      100              2  吉华集团  1304.027500  sh  stock_cn
603985 sh   603985      100              2  恒润股份    18.340000  sh  stock_cn
603986 sh   603986      100              2  兆易创新   110.000000  sh  stock_cn
603987 sh   603987      100              2   康德莱     6.130000  sh  stock_cn
603988 sh   603988      100              2  中电电机  1368.007500  sh  stock_cn
603989 sh   603989      100              2  艾华集团    22.049999  sh  stock_cn
603990 sh   603990      100              2  麦迪科技    36.240002  sh  stock_cn
603991 sh   603991      100              2  至正股份    18.270000  sh  stock_cn
603993 sh   603993      100              2  洛阳钼业     4.730000  sh  stock_cn
603996 sh   603996      100              2  中新科技    72.040000  sh  stock_cn
603997 sh   603997      100              2  继峰股份   728.057500  sh  stock_cn
603998 sh   603998      100              2  方盛制药     6.110000  sh  stock_cn
603999 sh   603999      100              2  读者传媒     5.580000  sh  stock_cn

[3549 rows x 7 columns]

### 2.股票日线

In [14]:
QA.QA_fetch_get_stock_day('tdx','000001','2018-08-01','2018-08-10',if_fq='bfq')

,open,close,high,low,vol,amount,date,code,date_stamp
date,,,,,,,,,
2018-08-01,9.42,9.15,9.50,9.11,814081.0,759282240.0,2018-08-01,000001,1.533053e+09
2018-08-02,9.13,8.94,9.15,8.88,931401.0,839272256.0,2018-08-02,000001,1.533139e+09
2018-08-03,8.93,8.91,9.10,8.91,476546.0,428641536.0,2018-08-03,000001,1.533226e+09
2018-08-06,8.94,8.94,9.11,8.89,554010.0,497906688.0,2018-08-06,000001,1.533485e+09
2018-08-07,8.96,9.17,9.17,8.88,690423.0,624359680.0,2018-08-07,000001,1.533571e+09
2018-08-08,9.16,9.05,9.16,9.04,578953.0,527526976.0,2018-08-08,000001,1.533658e+09
2018-08-09,9.04,9.29,9.35,9.02,806783.0,746469824.0,2018-08-09,000001,1.533744e+09
2018-08-10,9.30,9.23,9.32,9.16,424168.0,391366336.0,2018-08-10,000001,1.533830e+09

### 3.股票分钟线

In [18]:
QA.QA_fetch_get_stock_min('tdx','000001','2018-08-30 09:30:00','2018-08-31 15:00:00')

,open,close,high,low,vol,amount,datetime,code,date,date_stamp,time_stamp,type
datetime,,,,,,,,,,,,
2018-08-30 09:31:00,10.27,10.28,10.28,10.26,1.520400e+06,1.561075e+07,2018-08-30 09:31:00,000001,2018-08-30,1.535558e+09,1.535593e+09,1min
2018-08-30 09:32:00,10.28,10.27,10.29,10.27,4.093000e+05,4.206112e+06,2018-08-30 09:32:00,000001,2018-08-30,1.535558e+09,1.535593e+09,1min
2018-08-30 09:33:00,10.27,10.31,10.32,10.26,9.171000e+05,9.434675e+06,2018-08-30 09:33:00,000001,2018-08-30,1.535558e+09,1.535593e+09,1min
2018-08-30 09:34:00,10.32,10.32,10.35,10.32,1.353300e+06,1.398551e+07,2018-08-30 09:34:00,000001,2018-08-30,1.535558e+09,1.535593e+09,1min
2018-08-30 09:35:00,10.33,10.32,10.33,10.30,1.455900e+06,1.502392e+07,2018-08-30 09:35:00,000001,2018-08-30,1.535558e+09,1.535593e+09,1min
2018-08-30 09:36:00,10.32,10.30,10.32,10.30,6.024000e+05,6.209240e+06,2018-08-30 09:36:00,000001,2018-08-30,1.535558e+09,1.535593e+09,1min
2018-08-30 09:37:00,10.30,10.30,10.32,10.29,1.106300e+06,1.140471e+07,2018-08-30 09:37:00,000001,2018-08-30,1.535558e+09,1.535593e+09,1min
2018-08-30 09:38:00,10.32,10.31,10.32,10.29,1.277900e+06,1.317305e+07,2018-08-30 09:38:00,000001,2018-08-30,1.535558e+09,1.535593e+09,1min
2018-08-30 09:39:00,10.30,10.28,10.31,10.28,6.833000e+05,7.029922e+06,2018-08-30 09:39:00,000001,2018-08-30,1.535558e+09,1.535593e+09,1min
2018-08-30 09:40:00,10.28,10.28,10.29,10.27,3.393000e+05,3.487379e+06,2018-08-30 09:40:00,000001,2018-08-30,1.535558e+09,1.535593e+09,1min
2018-08-30 09:41:00,10.28,10.30,10.30,10.28,6.424000e+05,6.612979e+06,2018-08-30 09:41:00,000001,2018-08-30,1.535558e+09,1.535593e+09,1min
2018-08-30 09:42:00,10.29,10.26,10.29,10.25,1.572800e+06,1.615962e+07,2018-08-30 09:42:00,000001,2018-08-30,1.535558e+09,1.535593e+09,1min
2018-08-30 09:43:00,10.26,10.24,10.26,10.23,6.001000e+05,6.147694e+06,2018-08-30 09:43:00,000001,2018-08-30,1.535558e+09,1.535593e+09,1min
2018-08-30 09:44:00,10.24,10.26,10.27,10.24,3.600000e+05,3.691396e+06,2018-08-30 09:44:00,000001,2018-08-30,1.535558e+09,1.535593e+09,1min
2018-08-30 09:45:00,10.27,10.27,10.28,10.25,5.416000e+05,5.562000e+06,2018-08-30 09:45:00,000001,2018-08-30,1.535558e+09,1.535594e+09,1min
2018-08-30 09:46:00,10.27,10.26,10.27,10.25,5.724000e+05,5.873743e+06,2018-08-30 09:46:00,000001,2018-08-30,1.535558e+09,1.535594e+09,1min
2018-08-30 09:47:00,10.26,10.26,10.27,10.26,3.851000e+05,3.952037e+06,2018-08-30 09:47:00,000001,2018-08-30,1.535558e+09,1.535594e+09,1min
2018-08-30 09:48:00,10.26,10.25,10.26,10.25,2.390000e+05,2.450591e+06,2018-08-30 09:48:00,000001,2018-08-30,1.535558e+09,1.535594e+09,1min
2018-08-30 09:49:00,10.26,10.25,10.26,10.24,3.537000e+05,3.624099e+06,2018-08-30 09:49:00,000001,2018-08-30,1.535558e+09,1.535594e+09,1min
2018-08-30 09:50:00,10.25,10.26,10.27,10.25,3.539000e+05,3.630670e+06,2018-08-30 09:50:00,000001,2018-08-30,1.535558e+09,1.535594e+09,1min
2018-08-30 09:51:00,10.27,10.27,10.27,10.26,5.035000e+05,5.167826e+06,2018-08-30 09:51:00,000001,2018-08-30,1.535558e+09,1.535594e+09,1min
2018-08-30 09:52:00,10.26,10.26,10.27,10.26,2.082000e+05,2.137288e+06,2018-08-30 09:52:00,000001,2018-08-30,1.535558e+09,1.535594e+09,1min
2018-08-30 09:53:00,10.27,10.26,10.27,10.26,2.081000e+05,2.135633e+06,2018-08-30 09:53:00,000001,2018-08-30,1.535558e+09,1.535594e+09,1min
2018-08-30 09:54:00,10.27,10.27,10.27,10.25,6.685000e+05,6.860688e+06,2018-08-30 09:54:00,000001,2018-08-30,1.535558e+09,1.535594e+09,1min
2018-08-30 09:55:00,10.28,10.28,10.30,10.28,1.643500e+06,1.690261e+07,2018-08-30 09:55:00,000001,2018-08-30,1.535558e+09,1.535594e+09,1min
2018-08-30 09:56:00,10.28,10.28,10.29,10.28,4.638000e+05,4.769580e+06,2018-08-30 09:56:00,000001,2018-08-30,1.535558e+09,1.535594e+09,1min
2018-08-30 09:57:00,10.28,10.27,10.28,10.26,7.922000e+05,8.136606e+06,2018-08-30 09:57:00,000001,2018-08-30,1.535558e+09,1.535594e+09,1min
2018-08-30 09:58:00,10.28,10.29,10.29,10.27,2.733000e+05,2.810572e+06,2018-08-30 09:58:00,000001,2018-08-30,1.535558e+09,1.535594e+09,1min
2018-08-30 09:59:00,10.29,10.27,10.29,10.27,2.565000e+05,2.634971e+06,2018-08-30 09:59:00,000001,2018-08-30,1.535558e+09,1.535594e+09,1min
2018-08-30 10:00:00,10.28,10.27,10.28,10.27,7.560000e+04,7.769481e+05,2018-08-30 10:00:00,000001,2018-08-30,1.535558e+09,1.535594e+09,1min
...,...,...,...,...,...,...,...,...,...,...,...,...
2018-08-31 14:31:00,10.23,10.21,10.23,10.21,5.420000e+05,5.540769e+06,2018-08-31 14:31:00,000001,2018-08-31,1.535645e+09,1.535697e+09,1min
2018-08-31 14:32:00,10.21,10.21,10.22,10.20,5.452000e+05,5.566198e+06,2018-08-31 14:32:00,000001,2018-08-31,1.535645e+09,1.535697e+09,1min
2018-08-31 14:33:00,10.21,10.18,10.21,10.18,3.402900e+06,3.470408e+07,2018-08-31 14:33:00,000001,2018-08-31,1.535645e+09,1.535697e+09,1min
2018-08-31 14:34:00,10.18,10.19,10.19,10.17,5.893000e+05,5.998046e+06,2018-08-31 14:34:00,000001,2018-08-31,1.535645e+09,1.535697e+09,1min
2018-08-31 14:35:00,10.19,10.17,10.19,10.17,3.859000e+05,3.926942e+06,2018-08-31 14:35:00,000001,2018-08-31,1.535645e+09,1.535697e+09,1min
2018-08-31 14:36:00,10.17,10.17,10.18,10.17,3.799000e+05,3.865206e+06,2018-08-31 14:36:00,000001,2018-08-31,1.535645e+09,1.535697e+09,1min
2018-08-31 14:37:00,10.17,10.17,10.18,10.17,4.144000e+05,4.216120e+06,2018-08-31 14:37:00,000001,2018-08-31,1.535645e+09,1.535697e+09,1min
2018-08-31 14:38:00,10.18,10.17,10.18,10.17,4.573000e+05,4.652082e+06,2018-08-31 14:38:00,000001,2018-08-31,1.535645e+09,1.535697e+09,1min
2018-08-31 14:39:00,10.17,10.17,10.18,10.17,5.445000e+05,5.538968e+06,2018-08-31 14:39:00,000001,2018-08-31,1.535645e+09,1.535698e+09,1min
2018-08-31 14:40:00,10.17,10.15,10.17,10.15,9.291000e+05,9.436313e+06,2018-08-31 14:40:00,000001,2018-08-31,1.535645e+09,1.535698e+09,1min
2018-08-31 14:41:00,10.15,10.15,10.16,10.14,5.109000e+05,5.185022e+06,2018-08-31 14:41:00,000001,2018-08-31,1.535645e+09,1.535698e+09,1min
2018-08-31 14:42:00,10.15,10.15,10.16,10.14,9.724000e+05,9.871421e+06,2018-08-31 14:42:00,000001,2018-08-31,1.535645e+09,1.535698e+09,1min
2018-08-31 14:43:00,10.16,10.16,10.16,10.15,4.648000e+05,4.720947e+06,2018-08-31 14:43:00,000001,2018-08-31,1.535645e+09,1.535698e+09,1min
2018-08-31 14:44:00,10.16,10.16,10.16,10.15,3.173000e+05,3.222478e+06,2018-08-31 14:44:00,000001,2018-08-31,1.535645e+09,1.535698e+09,1min
2018-08-31 14:45:00,10.16,10.13,10.16,10.13,8.743000e+05,8.869773e+06,2018-08-31 14:45:00,000001,2018-08-31,1.535645e+09,1.535698e+09,1min
2018-08-31 14:46:00,10.14,10.13,10.14,10.12,1.389800e+06,1.408035e+07,2018-08-31 14:46:00,000001,2018-08-31,1.535645e+09,1.535698e+09,1min
2018-08-31 14:47:00,10.13,10.13,10.13,10.12,7.476000e+05,7.568508e+06,2018-08-31 14:47:00,000001,2018-08-31,1.535645e+09,1.535698e+09,1min
2018-08-31 14:48:00,10.13,10.14,10.14,10.12,9.508000e+05,9.631708e+06,2018-08-31 14:48:00,000001,2018-08-31,1.535645e+09,1.535698e+09,1min
2018-08-31 14:49:00,10.14,10.14,10.15,10.13,5.561000e+05,5.636948e+06,2018-08-31 14:49:00,000001,2018-08-31,1.535645e+09,1.535698e+09,1min
2018-08-31 14:50:00,10.14,10.13,10.15,10.13,8.168000e+05,8.277500e+06,2018-08-31 14:50:00,000001,2018-08-31,1.535645e+09,1.535698e+09,1min
2018-08-31 14:51:00,10.13,10.12,10.13,10.12,1.186200e+06,1.201001e+07,2018-08-31 14:51:00,000001,2018-08-31,1.535645e+09,1.535698e+09,1min
2018-08-31 14:52:00,10.13,10.13,10.14,10.13,8.083000e+05,8.189148e+06,2018-08-31 14:52:00,000001,2018-08-31,1.535645e+09,1.535698e+09,1min
2018-08-31 14:53:00,10.12,10.12,10.13,10.11,1.092700e+06,1.106054e+07,2018-08-31 14:53:00,000001,2018-08-31,1.535645e+09,1.535698e+09,1min
2018-08-31 14:54:00,10.12,10.12,10.12,10.11,5.244000e+05,5.305932e+06,2018-08-31 14:54:00,000001,2018-08-31,1.535645e+09,1.535698e+09,1min
2018-08-31 14:55:00,10.12,10.13,10.13,10.11,1.378700e+06,1.394839e+07,2018-08-31 14:55:00,000001,2018-08-31,1.535645e+09,1.535698e+09,1min
2018-08-31 14:56:00,10.12,10.12,10.13,10.11,1.495000e+06,1.513084e+07,2018-08-31 14:56:00,000001,2018-08-31,1.535645e+09,1.535699e+09,1min
2018-08-31 14:57:00,10.12,10.12,10.14,10.12,6.083000e+05,6.157596e+06,2018-08-31 14:57:00,000001,2018-08-31,1.535645e+09,1.535699e+09,1min
2018-08-31 14:58:00,10.13,10.13,10.13,10.13,9.500000e+03,9.623501e+04,2018-08-31 14:58:00,000001,2018-08-31,1.535645e+09,1.535699e+09,1min
2018-08-31 14:59:00,10.13,10.13,10.13,10.13,5.877472e-39,5.877472e-39,2018-08-31 14:59:00,000001,2018-08-31,1.535645e+09,1.535699e+09,1min
2018-08-31 15:00:00,10.13,10.13,10.13,10.13,3.236600e+06,3.278676e+07,2018-08-31 15:00:00,000001,2018-08-31,1.535645e+09,1.535699e+09,1min

### 4. 股票分笔数据